apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/component-name: sas-cleanwork
  name: sas-cleanwork
  labels:
    app.kuberentes.io/name: sas-cleanwork
    workload.sas.com/class: compute
    sas.com/admin: namespace
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sas.com/kustomize-base: base
          labels:
            app.kubernetes.io/name: sas-cleanwork
            workload.sas.com/class: compute
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: In
                    values:
                    - compute
                weight: 100
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: NotIn
                    values:
                    - cas
                    - stateful
                    - stateless
                weight: 50
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kuberentes.azure.com/mode
                    operator: NotIn
                    values:
                    - system
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
              requiredDuringSchedulingIgnoredDuringExecution: []
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
              requiredDuringSchedulingIgnoredDuringExecution: []
          containers:
          - env:
            - name: SSL_CERT_FILE
              value: /security/ca.crt
            envFrom:
            - configMapRef: 
                name: sas-go-config
            - secretRef:
                name: sas-consul-client
            image: sas-config-init
            name: sas-cleanwork
            resources:
              limits: 
                cpu: 500m
                memory: 500Mi
              requests:
                cpu: 50m
                memory: 50Mi
            securityContext:
              allowPrivilegeEscalation: true
              capabilities:
                add:
                - CAP_SYS_ADMIN
              privileged: true
              readOnlyRootFilesystem: true
              runAsNonRoot: false
              runAsUser: 0
            volumeMounts:
            - name: saswork
              mountPath: /saswork
            - name: security
              mountPath: /security
            - name: tmp
              mountPath: /tmp
            - name: sas-cleanwork-script
              mountPath: /sas-cleanwork-script
            command:
              - /bin/bash
              - -c
              - | 
                /sas-cleanwork-script/sas-cleanwork.sh
          imagePullSecrets: []
          restartPolicy: Never
          securityContext:
            runAsNonRoot: false
            seccompProfile: 
              type: RuntimeDefault
          tolerations:
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: compute
          volumes:
          - name: security
            secret:
              secretName: sas-consul-server-0
          - name: sas-cleanwork-script
            configMap:
              name: sas-cleanwork-script
              defaultMode: 511
          - name: tmp
            emptyDir: {}