apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    sas.com/admin: cluster-wide
    sas.com/deployment: sas-viya
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain