apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    sas.com/admin: cluster-wide
    sas.com/deployment: sas-viya
  name: saswork-pv
spec:
  capacity:
    storage:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/saswork
  nodeAffinity:
    required:
      nodeSelectorTerms: []