kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    sas.com/admin: cluster-local
    sas.com/deployment: sas-viya
  name: saswork-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: